# Program B default config
canonical_root: /data02/shiojiri/ILS/ILS_data/ERA5/era5_canonical
output_root: /data02/shiojiri/ILS/ILS_data/ERA5/out
python_cmd: singularity exec /data10/imageshare/shiojiri/pyenv.sif python3
chunks_time: 6
dask_num_workers: 1
dask_scheduler: threads
method: conservative
progress: auto
overwrite: false
