# Program A default config
input_root: /data02/shiojiri/DATA/ERA5/download/reanalysis-era5-single-levels/
output_root: /data02/shiojiri/ILS/ILS_data/ERA5/era5_canonical
python_cmd: singularity exec /data10/imageshare/shiojiri/pyenv.sif python3
lat_order: descending
chunks_time: 6
dask_num_workers: 1
dask_scheduler: threads
progress: auto
overwrite: false
